components:
  parameters:
    BookId:
      explode: false
      in: path
      name: bookId
      required: true
      schema:
        type: string
      style: simple
  responses:
    BadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Invalid request parameters
    NotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Resource not found
  schemas:
    Book:
      properties:
        author:
          type: string
        id:
          type: string
        price:
          format: float
          type: number
        publishedDate:
          format: date
          type: string
        title:
          type: string
      required:
      - author
      - id
      - title
      type: object
    Error:
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    NewBook:
      allOf:
      - $ref: '#/components/schemas/Book'
      required:
      - author
      - title
    Order:
      properties:
        bookId:
          type: string
        orderId:
          type: string
        quantity:
          type: integer
        status:
          enum:
          - pending
          - shipped
          - delivered
          type: string
        totalPrice:
          format: float
          type: number
      type: object
    OrderRequest:
      properties:
        bookId:
          type: string
        quantity:
          minimum: 1
          type: integer
      required:
      - bookId
      - quantity
      type: object
  securitySchemes:
    default:
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
      type: oauth2
info:
  contact:
    email: support@bookstore.example.com
    name: API Support
  description: |
    A simple REST API to browse and purchase books.
  title: BookstoreAPI
  version: 1.0.0
openapi: 3.0.0
paths:
  /books:
    get:
      operationId: listBooks
      parameters:
      - description: Filter by author name
        explode: true
        in: query
        name: author
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Book'
                type: array
          description: A JSON array of book objects
      security:
      - default: []
      summary: List all books
      tags:
      - books
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];

        if (!responses[200]) {
         responses [200] = [];
        }
        responses[200]["application/json"] = [ {
          "id": "123e4567-e89b-12d3-a456-426614174000",
          "title": "The Great Gatsby",
          "author": "F. Scott Fitzgerald",
          "publishedDate": "1925-04-10",
          "price": 10.99
        }
        ,
        {
          "id": "42",
          "title": "To Kill a Mockingbird",
          "author": "Harper Lee",
          "publishedDate": "1960-07-11",
          "price": 8.50
        }
          ];

        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 200;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json"; // assign whatever available
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
    post:
      operationId: createBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
        required: true
      responses:
        "201":
          description: Book created
          headers:
            Location:
              description: URL of the new book
              explode: false
              schema:
                type: string
              style: simple
      security:
      - default: []
      summary: Add a new book
      tags:
      - books
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];
        if (!responses[201]) {
          responses[201] = [];
        }
        responses[201]["application/json"] = "";
        responses[201]["application/xml"] = "";


        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 201;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json";
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        } else if (accept == "application/xml") {
         mc.setProperty('CONTENT_TYPE', 'application/xml');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadXML(responses[responseCode]["application/xml"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /books/{bookId}:
    delete:
      operationId: deleteBook
      responses:
        "204":
          description: Book deleted
      security:
      - default: []
      summary: Delete a book
      tags:
      - books
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];
        if (!responses[204]) {
          responses[204] = [];
        }
        responses[204]["application/json"] = "";
        responses[204]["application/xml"] = "";


        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 204;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json";
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        } else if (accept == "application/xml") {
         mc.setProperty('CONTENT_TYPE', 'application/xml');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadXML(responses[responseCode]["application/xml"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
    get:
      operationId: getBook
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: Book details
        "404":
          $ref: '#/components/responses/NotFoundError'
      security:
      - default: []
      summary: Get a book by ID
      tags:
      - books
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];

        if (!responses[200]) {
         responses [200] = [];
        }
        responses[200]["application/json"] = {
          "id" : "string",
          "title" : "string",
          "author" : "string",
          "publishedDate" : "2015-07-20",
          "price" : 1.1
        };
        if (!responses[404]) {
          responses[404] = [];
        }
        responses[404]["application/json"] = "";
        responses[404]["application/xml"] = "";


        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 200;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json";
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        } else if (accept == "application/xml") {
         mc.setProperty('CONTENT_TYPE', 'application/xml');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadXML(responses[responseCode]["application/xml"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
    parameters:
    - $ref: '#/components/parameters/BookId'
    put:
      operationId: updateBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "200":
          description: Book updated
      security:
      - default: []
      summary: Update a book
      tags:
      - books
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];
        if (!responses[200]) {
          responses[200] = [];
        }
        responses[200]["application/json"] = "";
        responses[200]["application/xml"] = "";


        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 200;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json";
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        } else if (accept == "application/xml") {
         mc.setProperty('CONTENT_TYPE', 'application/xml');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadXML(responses[responseCode]["application/xml"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /orders:
    post:
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: Order placed
        "400":
          $ref: '#/components/responses/BadRequestError'
      security:
      - default: []
      summary: Place a book order
      tags:
      - orders
      x-auth-type: Application & Application User
      x-mediation-script: |-
        var accept = mc.getProperty('AcceptHeader');
        var responseCode = mc.getProperty('query.param.responseCode');
        var responseCodeSC;
        var responses = [];

        if (!responses[201]) {
         responses [201] = [];
        }
        responses[201]["application/json"] = {
          "orderId" : "string",
          "bookId" : "string",
          "quantity" : 0,
          "totalPrice" : 1.1,
          "status" : "pending"
        };
        if (!responses[400]) {
          responses[400] = [];
        }
        responses[400]["application/json"] = "";
        responses[400]["application/xml"] = "";


        responses[501] = [];
        responses[501]["application/json"] = {
        "code" : 501,
        "description" : "Not Implemented"}
        responses[501]["application/xml"] = <response><code>501</code><description>Not Implemented</description></response>;

        if (responseCode == null) {
         responseCode = 201;
        }

        if (!responses[responseCode]) {
          if (responses["default"]) {
            responseCode = "default"
          } else {
            responseCode = 501;
          }
        }
        if (responseCode === "default") {
          responseCodeSC = mc.getProperty('query.param.responseCode');
        } else {
          responseCodeSC = responseCode;
        }
        if (accept == null || !responses[responseCode][accept]) {
         accept = "application/json";
        }

        if (accept == "application/json") {
         mc.setProperty('CONTENT_TYPE', 'application/json');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadJSON(responses[responseCode]["application/json"]);
        } else if (accept == "application/xml") {
         mc.setProperty('CONTENT_TYPE', 'application/xml');
         mc.setProperty('HTTP_SC', responseCodeSC + "");
         mc.setPayloadXML(responses[responseCode]["application/xml"]);
        }
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
security:
- default: []
servers:
- description: Production server
  url: https://api.bookstore.example.com/v1
tags:
- description: Operations on books
  name: books
- description: Customer orders
  name: orders
x-wso2-api-key-header: ApiKey
x-wso2-application-security:
  optional: false
  security-types:
  - oauth2
x-wso2-auth-header: Authorization
x-wso2-basePath: /bookstoreapi/1.0.0
x-wso2-cors:
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  - Internal-Key
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
  accessControlAllowOrigins:
  - '*'
  corsConfigurationEnabled: false
x-wso2-production-endpoints:
  type: http
  urls:
  - http://localhost
x-wso2-response-cache:
  cacheTimeoutInSeconds: 300
  enabled: false
x-wso2-sandbox-endpoints:
  type: http
  urls:
  - http://localhost
x-wso2-transports:
- http
- https
